---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: win2012r2
    driver:
      box: eval-win2012r2-standard-chef12.0.3-1.0.4
      vm_hostname: win2012r2

suites:
  - name: default
    run_list:
      - recipe[winsw::_winsw_integration_fixture]
