---
driver:
  name: vagrant

provisioner:
  name: windows_chef_zero
  root_path: c:/windows/temp/kitchen
  ruby_bindir: c:/opscode/chef/embedded/bin
  require_chef_omnibus: false

platforms:
  - name: win2012r2
    transport:
      name: ssh
    driver:
      box: eval-win2012r2-standard-cheflatest-1.0.4
      vm_hostname: win2012r2

suites:
  - name: default
    run_list:
      - recipe[fake::default]