---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: win2012r2
    transport:
      name: winrm
    driver:
      box: eval-win2012r2-standard-cheflatest-1.0.4
      vm_hostname: win2012r2

suites:
  - name: default
    run_list:
      - recipe[fake::default]